### ISSUE TITLE
Porting the website to use Laravel

### ISSUE THREAD

**Issue by geo-vi** [yusufsahinhamza/darkorbit-cms#1]
I've seen your repo and it's pretty fresh. Try porting it to https://laravel.com/
It will prevent you from causing many major architecture failures and as I see you've already got some.
You can see a great implementation of a Laravel Boilerplate here: https://github.com/rappasoft/laravel-boilerplate
Follow the guidelines and you can always message me on FB if you struggle.
Good luck ;)

**Comment by yusufsahinhamza** [comment]
Thanks for your advice! 

I decided to do it in the new repo (https://github.com/yusufsahinhamza/laravel-darkorbit-cms) in my free times :)
