### ISSUE TITLE
SWF elements on HTTPS domain

### ISSUE THREAD

**Issue by LabodiDavid** [yusufsahinhamza/darkorbit-cms#2]
Hello! Keep up doing this good work, this project and the code is really good. 👍 
I have a question, how can i make the equipment and the spacemap, so the swf elements to work on a https domain? Or is it currently unavailable for some reasons cause like the localhost isn't working while the 127.0.0.1 works?
And a second question, I got so many errors like this 
`Mixed Content: The page at 'https://mydomain/map-revolution' was loaded over HTTPS, but requested an insecure plugin data 'http://mydomain/spacemap/templates/en/resource_loadingScreen.xml?__cv=d91fded96e68047511edfddc4231bc00'. This content should also be served over HTTPS.`
Almostly for all the files in **spacemap**, and **flashAPI** folder. How is it possible to redirect these to https?
I'm changed the defined DOMAIN in the **config.php** to my domain with https prefix, everything is work except the flash elements.
And if it matters, I have set up https redirect in nginx.
Thank you in advance!

![image](https://user-images.githubusercontent.com/40663270/80364363-12c33680-8886-11ea-8cf8-8cb1e3ebf5bd.png)

**Comment by yusufsahinhamza** [comment]
You can try to set `cdn` in the `map_revolution.php` to domain name that includes `HTTPS`:

https://github.com/yusufsahinhamza/darkorbit-cms/blob/a9397ef7929fafda4c7792e680c70e9445a5fcf1/files/external/map_revolution.php#L111

to

```
cdn": "<?php echo DOMAIN; ?>
```

**NOTE:** Make sure you already set your defined DOMAIN to a link includes `HTTPS`.

Also you can force/redirect users to load website over `HTTPS` with `.htaccess` file, just like in that example: https://stackoverflow.com/a/10489949

**Comment by LabodiDavid** [comment]
I set a "cdn" with https prefix, but didn't work.
As I said i set up a https redirect in the nginx reverse proxy. I tried your apache https redirect, but these are give err_too_many_redirects error, or didn't work.
These mixed content errors are occuring only when i load a page with flash content, so on the **equipment**, and on the **map-revolution**.
When I trying to open for example the flashAPI/inventory.php my browser is redirected to https, but on the equipment page, i get mixed content error for it.

**Comment by yusufsahinhamza** [comment]
I dont actually know how to fix this issue, i didn't try to use HTTPS domain for a DarkOrbit private server but i think there should be something in the /spacemap/main.swf that trying to force flash contents with HTTP domain that's why you are are getting these errors; using HTTPS domain for see a flash content (like spacemap/equipment) and loaded any HTTP domain content is not secure so browser blocking to load them.

I recommend you to check /spacemap/main.swf, that's the only thing i can do for you so i'm closing this issue.
