### ISSUE TITLE
Starting the game results in endless "Loading"

### ISSUE THREAD

**Issue by hypixus** [yusufsahinhamza/darkorbit-cms#3]
![image](https://user-images.githubusercontent.com/13383985/83201000-dadd3680-a144-11ea-9bcf-61524777a598.png)

Preety much self explanatory.
I used latest XAMPP for mysql and php servers, created a new account with manual verification(changing value in database record), and pressed "start". Game is basically stuck at loading endlessly.

**Comment by yusufsahinhamza** [comment]
@hypixus If you are trying to start the game with "localhost" address; it may stuck for forever like that. Try to start the game with "127.0.0.1" address instead.

As far as i remember there is a if statement/control in the main.swf which is dont want you to start the game with "localhost" address directly.

**Comment by yusufsahinhamza** [comment]
Hello again, i'm closing this issue due there is no comment anymore, feel free to open it if you need to ask more questions about this issue.
