### ISSUE TITLE
Implementation to database? 

### ISSUE THREAD

**Issue by Takiusu** [yusufsahinhamza/darkorbit-cms#4]
Good morning! Im still using your emulator, but your database missing many things, such as ships, maps and npces. Can you help me to add them all? I started adding maps with portails and i have added 50% of them already, but i i need more information and your help.

**Comment by yusufsahinhamza** [comment]
@Rayvakarian Hello, i'm not working on this project anymore, but you can ask questions others on elitepvpers to get help.
